// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEHi2JOTmmic-h2-COB2vmhCeTD_jN23E',
    appId: '1:303807188594:android:8888c2602fa46763e87ceb',
    messagingSenderId: '303807188594',
    projectId: 'barback-a5afe',
    storageBucket: 'barback-a5afe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXXCUDQyHKUQPd80jB503QKyP2Gmi68ys',
    appId: '1:303807188594:ios:5b6f55a23c79213ee87ceb',
    messagingSenderId: '303807188594',
    projectId: 'barback-a5afe',
    storageBucket: 'barback-a5afe.firebasestorage.app',
    androidClientId: '303807188594-j19m0gk6bebsfp7n2d8avj6e5sb9b1ua.apps.googleusercontent.com',
    iosClientId: '303807188594-t1aq10tmtmgq7jdqjinjb2ejimooghmq.apps.googleusercontent.com',
    iosBundleId: 'io.stewart.flutterProjects',
  );
}
